version: "3.7"
services:
  server:
    build: server/.
    depends_on: 
      - nats
      - jaeger
    ports:
      - "8080:8080"
    environment: 
      JAEGER_AGENT_HOST: host.docker.internal
      JAEGER_AGENT_PORT: 6831
      JAEGER_SERVICE_NAME: server
      JAEGER_SAMPLER_PARAM: "1"
      JAEGER_SAMPLER_TYPE: const
  subscriber:
    build: messaging/.
    depends_on:
      - nats
      - jaeger
    environment: 
      URL: nats://host.docker.internal:4222
      JAEGER_AGENT_HOST: host.docker.internal
      JAEGER_AGENT_PORT: 6831
      JAEGER_SERVICE_NAME: server
      JAEGER_SAMPLER_PARAM: "1"
      JAEGER_SAMPLER_TYPE: const
  nats:
    image: nats-streaming
    ports: 
      - "4222:4222"
      - "8222:8222"
  jaeger:
    image: jaegertracing/all-in-one:1.14
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  